### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hx364** [mortehu/text-classifier#1]
Hi,

This project is really great, and I am considering to use it for my project. But I am not sure how to install it, and there is no documentation on that. can you give any instruction on installation?

I install the dependencies and tried the common './configure, make' way. Get the error message:

```
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CAPNP... no
configure: error: Package requirements (capnp) were not met:

No package 'capnp' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CAPNP_CFLAGS
and CAPNP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Saying that capping not found, but it is already installed and I can use it in bash.

```
xutekiMacBook-Pro:text-classifier how$ capnp
capnp: missing command
Try 'capnp --help' for more information.
xutekiMacBook-Pro:text-classifier how$ capnp --help
Usage: capnp [<option>...] <command> [<arg>...]

Command-line tool for Cap'n Proto development and debugging.

Commands:
  compile  Generate source code from schema files.
  decode   Decode binary Cap'n Proto message to text.
  encode   Encode text Cap'n Proto message to binary.
  eval     Evaluate a const from a schema file.
  id       Generate a new unique ID.

See 'capnp help <command>' for more information on a specific command.
```

Thanks! Any help appreciated.

**Comment by mortehu** [comment]
Very old versions of Cap'n Proto do not provide `capnp.pc`, which is required by `pkg-config`.  If you have a new version, the file must have been installed in a non-standard location, which you can specify using `PKG_CONFIG_PATH`.  If you do not have this file, which was [added to Cap'n Proto in 2013](https://github.com/sandstorm-io/capnproto/commit/b15789d8457d53b8d99881f802b31025be7e3277), please install a newer version of Cap'n Proto (at least version 0.5).
